@startuml
skinparam classAttributeIconSize 0

abstract class Дети {
    + любовь
}

class Герда extends Дети {
    + плакать()
    + сила = 10
}

class Кай extends Дети {
    + собирать слово()
}

class Королева  {
    + жестокость
    + украсть мальчика()
}


abstract class Сердце {
    + состояние: String
}

class РастопленноеСердце extends Сердце {
    состояние: String = "Растопленное"
}

class ЗамороженноеЗамороженное extends Сердце {

    состояние: String = "Замороженное"
}
class Льдинка {
    + прочность = 10
}


' СВЯЗИ
Королева --> Кай : крадёт >
Герда --> Льдинка : плачет >
Льдинка --> Сердце : состояние >


note right of Льдинка
  if (прочность !=0) 
    return ЗамороженноеСердце()
  else 
    return РастопленноеСердце()
end note

@enduml
